Fix TypeError with Python 2.6 and Plone.
TypeError: super() argument 1 must be type, not classobj

The logging.Handler is not a classobj in python 2.6, so we can't use super.